Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [2]:
import numpy as np

a = np.random.random((10,3))
print(a)
print("RESULT: ", a[np.arange(10), np.argmin(abs(a - 0.5), axis = 1)])

[[0.32053301 0.46016808 0.03829504]
 [0.46985303 0.13156413 0.73746351]
 [0.5703398  0.96074247 0.97795517]
 [0.35967313 0.93128984 0.16829526]
 [0.06446642 0.53794867 0.13812964]
 [0.69535739 0.05513064 0.83137073]
 [0.90875811 0.5757109  0.81879126]
 [0.44905296 0.17819375 0.95777559]
 [0.17898055 0.46299185 0.81684982]
 [0.29025721 0.60290294 0.64694807]]
RESULT:  [0.46016808 0.46985303 0.5703398  0.35967313 0.53794867 0.69535739
 0.5757109  0.44905296 0.46299185 0.60290294]


Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [20]:
a = np.random.random((6, 6))
print(a)
print("\n  RESULT: ", np.sum(a, axis = 1) / np.min(a, axis = 0))

[[0.68494883 0.71659248 0.31186937 0.08973734 0.22510634 0.19707431]
 [0.51173329 0.24312195 0.64933806 0.23570247 0.96723173 0.85412986]
 [0.68516932 0.07972543 0.3342413  0.93007714 0.57290693 0.13506844]
 [0.96742515 0.4880297  0.16808339 0.46476841 0.05772227 0.14988542]
 [0.04383974 0.33075919 0.2119013  0.20279518 0.22593156 0.54637243]
 [0.31334867 0.27301574 0.92047839 0.54119614 0.16939112 0.08629108]]

  RESULT:  [50.76053762 43.41472387 16.28470568 25.58482723 27.05367328 26.6970948 ]


На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [53]:
x = np.array([6,2,0,3,0,0,5,7,0])
print(x)
print("RESULT: ", np.max(np.array([x[i] for i in np.arange(1, len(x)) if (x[i - 1] == 0)])))

[6 2 0 3 0 0 5 7 0]
RESULT:  5


Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [40]:
x = np.ones(10)
i = np.array([0,1,2,3,5,5,5,8])

for k in i:
    x[k]+=1

print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


Написать функцию, реализующую алгоритм k-means. Входные и выходные значения функции должны быть аналогичны https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.vq.kmeans.html. Функция должна содержать только один цикл while (for).

In [1]:
import numpy as np

def kmeans(obs, number_of_clasters, iter_max=20, distorion_min=1e-05):
    distortion = 1. #initial distance
    iter=0

    centroids = np.array([obs[i] for i in range(0,k)]) #initial centroids
    clasters = np.array((k,len(obs)))

    while ((delta > delta_min) and (iter<iter_max)):
         b = np.argmin(clasters - centroids, axis = 1)
         


    return 0

С помощью реализованной функции kmeans выделить кластеры клиентов в разрезах возраст-доход, возраст-покупательский индекс, доход-покупательский индекс. В каждом случае использовать elbow method для определения оптимального числа кластеров. Визуализировать полученные кластеры (каждый кластер изобразить собственным цветом). Дать интерпретацию полученным кластерам.