1. Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [1]:
import numpy as np
a = np.random.random((10,3))
print(a)
print("RESULT: ", a[np.arange(10), np.argmin(abs(a - 0.5), axis = 1)])

[[0.95728647 0.95138015 0.15940698]
 [0.61407168 0.42820738 0.30976212]
 [0.6597772  0.92762836 0.57187851]
 [0.39085069 0.75555271 0.6973926 ]
 [0.19904519 0.63208397 0.456853  ]
 [0.14195466 0.93433012 0.75698323]
 [0.15206607 0.33424355 0.23322196]
 [0.0221466  0.24055479 0.62298175]
 [0.17447446 0.82893541 0.18529946]
 [0.55071289 0.49860278 0.17038693]]
RESULT:  [0.15940698 0.42820738 0.57187851 0.39085069 0.456853   0.75698323
 0.33424355 0.62298175 0.18529946 0.49860278]


2. Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [4]:
a = np.random.random((6, 6))
print(a)
print("RESULT: ", np.sum(a, axis = 1) / np.min(a, axis = 0))

[[0.72994897 0.09725398 0.55206529 0.28310416 0.52035115 0.79432403]
 [0.71368857 0.84528733 0.02557738 0.92167628 0.79587798 0.09372724]
 [0.58938131 0.37321721 0.84133174 0.37973491 0.50351028 0.21785218]
 [0.60014962 0.92049709 0.48806878 0.77059582 0.07146975 0.42382813]
 [0.29523521 0.7980708  0.58928956 0.60652157 0.77352758 0.98772889]
 [0.16599988 0.58999946 0.71689116 0.22517705 0.05965578 0.57061215]]
RESULT:  [ 17.9340349   34.91717988 113.57801589  14.54237557  67.89574363
  24.8416094 ]


3. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [6]:
x = np.array([6,2,0,3,0,0,5,7,0])
print(x)
print("RESULT: ", np.max(np.array([x[i] for i in np.arange(1, len(x)) if (x[i - 1] == 0)])))

[6 2 0 3 0 0 5 7 0]
RESULT:  5


4. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [18]:
x = np.ones(10)
i = np.array([0,1,2,3,5,5,5,8])
x[i]+=np.bincount(i)[i]
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
